# Generated by Django 4.2.2 on 2023-06-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionForm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markmodel',
            old_name='neet_total_neet_percentile',
            new_name='neet_total_percentile',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='date_of_admission',
            field=models.DateField(default=None, null=True),
        ),
    ]
