# Generated by Django 4.2.2 on 2023-06-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markmodel',
            name='allotment_order_data',
            field=models.DateField(blank=True, default=None),
        ),
    ]
