# Generated by Django 4.2.2 on 2023-06-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionForm', '0002_alter_markmodel_allotment_order_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markmodel',
            name='allotment_order_data',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
