# Generated by Django 4.2.2 on 2023-06-22 09:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionForm', '0002_rename_neet_total_neet_percentile_markmodel_neet_total_percentile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='guardian_mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='mobile_1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='mobile_2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='mobile_3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='student_contact_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='student_email_id',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='allotment_order_data',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='board_of_study',
            field=models.CharField(blank=True, choices=[('State', 'State'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('Others', 'Others')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='hsc_biology_mark',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='hsc_chemistry_mark',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='hsc_marks_maximum',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='hsc_physics_mark',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='hsc_total_mark',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='hsc_year_of_passing',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='neet_air',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='neet_biology_mark',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='neet_biology_percentile',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=11, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='neet_chemistry_mark',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='neet_chemistry_percentile',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=11, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='neet_physics_mark',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='neet_physics_percentile',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=11, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='neet_roll_no',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='neet_total_mark',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(720)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='neet_total_percentile',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=11, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='neet_year',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='no_of_neet_attempts',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='pcb_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='selection_committee_allotment_order_no',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='selection_committee_general_rank',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='father_email',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='father_occupation',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='father_occupation_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='father_phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='mother_email',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='mother_occupation',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='mother_occupation_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='mother_phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='address_for_communication',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='address_local_guardian',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='admission_no',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='allotment_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='ar_number',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='caste',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='community',
            field=models.CharField(blank=True, choices=[('OC', 'OC'), ('BC', 'BC'), ('MBC', 'MBc'), ('SC', 'SC'), ('SCA', 'SCA'), ('ST', 'ST')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='contact_info',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdmissionForm.contactmodel'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='course',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='date_of_admission',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='date_of_joining',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.CharField(blank=True, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='general_rank',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='hsc_register_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='hsc_school_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='is_hostellite',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='mark_info',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdmissionForm.markmodel'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='medium_of_study',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='mother_tongue',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='native_place',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='neet_hall_ticket_no',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='neet_roll_no',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='parent_info',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdmissionForm.parentmodel'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='quota',
            field=models.CharField(blank=True, choices=[('Govt', 'Govt'), ('Mgt', 'Mgt'), ('NRI', 'NRI'), ('NRILapsed', 'NRILapsed')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='scholarship',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='serial_no',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='university_register_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
