# Generated by Django 4.2.2 on 2023-06-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionForm', '0003_alter_markmodel_allotment_order_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='markmodel',
            name='board_of_study',
            field=models.CharField(blank=True, choices=[('State', 'State'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('Others', 'Others')], default='', max_length=30),
        ),
    ]
