# Generated by Django 4.2.2 on 2023-06-22 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionForm', '0003_alter_contactmodel_guardian_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='status',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
    ]
